Build and deploy docs from travis
Build the docs in travis and deploy them to the sardana-doc repo using
doctr.

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -8,12 +8,18 @@ services:
   - docker
 
 python:
-  - "2.7"
+  - "3.6"
 
 env:
+  global:
+    # Doctr deploy key for sardana-org/sardana-doc
+    - secure: "p/0UgVZzPKJQqcvQ/97qMgo9kPCE0cZ6vI+308YEJ2o9xj4a3FsfHCZ/vWtjdsrp1sQbtKVDesx+xmK4CLDzQeC2+Xskv8OZDjaG2jYkHcVosZEM3EGW8rLVKzoDWLr6cTy2wexLgjHPCsmrjukPs49/i5p+WU0no64YoLlZdp9TT+gvWSQJLIk6R4eqt4FHMszPybLv0pvb1SEiCzimlX1WM1pBrE0LHgchd2ZBYSUWTTwe+Koi4HCS4Bads8j20K2e3fFKcmR2u9DfmU+7Mf5HRJsj1LYJgBUF76lUG2/fZfpoDe8sWi+eUewTa3zNM4bhRLpV+pmG0ypplM4pIcdvwiHV03nGSGu6XK6OGQ/Mgsw0fmud4JR4f5g9DgEfERlyJKI4A9mPZQ327OmEwOOl33x2AFJAL05Qvm0yXCkf1dwgYXnZl44SQbAczY1NHFL90t6xbHtmTitJrE2Xb+4BLzMe3OOZj6j/0QeiXA4z1FnZr1s8UoAsm68iW194IuFg1RRG9FTISFWaBew5wzwvAJak0DxkpG0k43VkHiVC7sPHqr5CxXMXO/MuaptK2ti6iLK9xBAEUpO9HluOkeJq5WDIIxBiBS9tPi0i3vIpq87RjHkdw5n7pdIqnuJ1nXUjpWsuUyV3fLkY12fFxSbZgqmNhIE5/o9c5VP/69Y="
+
+  matrix:
   - TEST="flake8"
   - TEST="testsuite" DOCKER_IMG=reszelaz/sardana-test
   - TEST="testsuite" DOCKER_IMG=reszelaz/sardana-test:taurus-support-3.x
+
 
 before_install:
   # install flake8 to perform python code style check in the script part
@@ -38,7 +44,27 @@ install:
   - if [ $TEST == "testsuite" ]; then docker exec sardana-test supervisorctl start MacroServer; fi
 
 script:
+  # make the script fail if a line fails
+  - set -e
   # run flake8 check on all python files in the project
   - if [ $TEST == "flake8" ]; then ci/flake8_diff.sh; fi
   # run the full testsuite
   - if [ $TEST == "testsuite" ]; then docker exec sardana-test sardanatestsuite; fi
+  # build & deploy sphinx docs to sardana-doc repo
+  - if [[ "$DOCKER_IMG" == "reszelaz/sardana-test" && "$TRAVIS_REPO_SLUG" == "sardana-org/sardana" ]]; then
+      docker exec -t sardana-test /bin/bash -c "cd /sardana ; python setup.py build_sphinx" ;
+      pip install doctr ;
+      docker exec sardana-test /bin/bash -c "touch /sardana/build/sphinx/html/.nojekyll" ;
+      if [[ "${TRAVIS_BRANCH}" == "develop" ]]; then
+        doctr deploy . ;
+      else
+        doctr deploy "v-$TRAVIS_BRANCH"  ;
+      fi;
+    fi
+
+doctr:
+  key-path : ci/github_deploy_key.enc
+  deploy-repo : sardana-org/sardana-doc
+  require-master: false
+  sync: true
+  built-docs: build/sphinx/html/
